import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import StarterImage from './StarterImage'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Jishnu Pavithran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.landing_page}>
          <div className={styles.left}>
            <h2 className={styles.title}>Jishnu Pavithran</h2>
            <p className={styles.subtitle}>A Full Stack Developer</p>
          </div>
          <div className="right">
          <StarterImage/>
          </div>
        </div>
      {/* <Image src="/programming.svg" alt="programming Logo" width={500} height={500} /> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
